### ISSUE TITLE
Setup of MVC-structure

### ISSUE THREAD

**Issue by oscarvik** [oddaspa/TDT4240#3]

**Comment by oddaspa** [comment]
## MVC Arcitecture

### Model
![image](https://user-images.githubusercontent.com/27822531/54991046-62b53700-4fbc-11e9-9582-835ed5d2269c.png)
Model Stores all data in a HashMap<String, Array<Sprites>>. This way we can use Model.internalData("menu") to get all relevant sprites for the menu state. To store functional classes e.g Helicopter.java class with methods such as update and shoot as a Sprite, we have extended the Sprite class and implemented a new AssetModel interface. This way we can cast the sprite and use Helicopter. java methods while still having a generic Sprite class. See below.
![image](https://user-images.githubusercontent.com/27822531/54991994-7497d980-4fbe-11e9-9b6b-fd430b1267a9.png)

### View
![image](https://user-images.githubusercontent.com/27822531/54992459-a2315280-4fbf-11e9-90ab-fef40fae7f8f.png)
The View.java class is not aware of which sprites it is rendering due to the generic Sprite extension mentioned above. To render to the screen the view simply iterates through the data passed down from the Model.java class. The only functionality View has is to send the touch coordiantes to the Controller class. 


### Controller
![image](https://user-images.githubusercontent.com/27822531/54990828-ede1fd00-4fbb-11e9-9a5f-28a2892341a6.png)
The Controller.java class hold the logic between the Model.java class and the View.java class. For now the view send screen coordinates of where the user touched the screen and sends them through the controller to the model. We do it this way to keep MVC architecture.
